import type { WatContext } from "../backends/wasm/wat-context.js";
import { Base, type GradMap, Num, Unary } from "./base.js";
import { mulAdjoint, negAdjoint } from "./grad.js";
import { Add, Divide, Minus, Mul } from "./nary.js";
import { Sqrt } from "./unary-special.js";

/**
 * Single-operand function nodes (absolute value, rounding, exponential,
 * logarithm, and the trigonometric / hyperbolic families plus their inverses).
 * Each wraps one `child` expression. See {@link Base} for the serialiser
 * contract; reciprocal/inverse forms are expressed in terms of the primitives
 * the runtime exposes (`Math.*`, `np.*`, the `$math_*` WAT imports).
 *
 * @module
 */

///////////////////////////////////////////////////////////////////////////////
// Unary fns
///////////////////////////////////////////////////////////////////////////////

/** Absolute value, `|child|`. */
export class Abs extends Unary {
  readonly nodeType = "Abs";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.abs(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `abs(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `abs(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><abs/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.abs ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[|child|] = child/|child| (undefined exactly at 0 — measure zero, same accepted convention as the other non-smooth nodes, ADR 0005 §2.2.1). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Divide([this.child, new Abs(this.child)]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Round up to the nearest integer, `⌈child⌉`. */
export class Ceiling extends Unary {
  readonly nodeType = "Ceiling";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.ceil(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `math.ceil(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\lceil ${this.child.toTex(texNames)} \\rceil`;
  }
  toSBML(): string {
    return `<apply><ceiling/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.ceil ${this.child.toWat(ctx)})`;
  }
  /** Piecewise-constant: zero gradient almost everywhere, undefined only at integer boundaries (measure zero) — ADR 0005 §2.2.1. */
  pushGradient(_adjoint: Base, _grads: GradMap): void {}
}

/** Natural exponential, `e^child`. */
export class Exp extends Unary {
  readonly nodeType = "Exp";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.exp(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.exp(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `e^{${this.child.toTex(texNames)}}`;
  }
  toSBML(): string {
    return `<apply><exp/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_exp ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[e^child] = e^child, i.e. this function itself. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    this.child.pushGradient(mulAdjoint(adjoint, new Exp(this.child)), grads);
  }
}

/** Factorial of the rounded operand, `round(child)!`. */
export class Factorial extends Unary {
  readonly nodeType = "Factorial";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    const n = this.child.toJs();
    return `((n => { let r = 1; for (let i = 2; i <= Math.round(n); i++) r *= i; return r; })(${n}))`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `math.factorial(int(round(${this.child.toPy(displayNames)})))`;
  }
  toTex(texNames: Map<string, string>): string {
    return `${this.child.toTex(texNames)}!`;
  }
  toSBML(): string {
    return `<apply><factorial/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_factorial ${this.child.toWat(ctx)})`;
  }
  /**
   * A proper derivative needs the digamma function (Γ'(x+1)/Γ(x+1)), which
   * isn't among the WAT math imports — not worth adding for a node that's
   * never generated by the NN-block generator and rare in hand-written
   * kinetic rate laws (ADR 0005 §2.2.1). Treated as gradient-zero.
   */
  pushGradient(_adjoint: Base, _grads: GradMap): void {}
}

/** Round down to the nearest integer, `⌊child⌋`. */
export class Floor extends Unary {
  readonly nodeType = "Floor";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.floor(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.floor(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\lfloor ${this.child.toTex(texNames)} \\rfloor`;
  }
  toSBML(): string {
    return `<apply><floor/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.floor ${this.child.toWat(ctx)})`;
  }
  /** Piecewise-constant, same convention as {@link Ceiling} — ADR 0005 §2.2.1. */
  pushGradient(_adjoint: Base, _grads: GradMap): void {}
}

/** Natural logarithm, `ln(child)`. The WAT form clamps the argument to ≥1e-30 so transient negative states during implicit solves don't produce NaNs. */
export class Ln extends Unary {
  readonly nodeType = "Ln";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.log(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.log(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\ln(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><ln/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    // Clamp to 1e-30 before log: RADAU5 Newton iterations can temporarily
    // drive state variables negative; log(<=0) = NaN cascades through all
    // derivatives. 1e-30 keeps pH_lu ≈ 30 (finite, bounded f64 downstream).
    return `(call $math_log (f64.max ${this.child.toWat(ctx)} (f64.const 1e-30)))`;
  }
  /**
   * d/dchild[ln(child)] = 1/child. Deliberately not clamped to match the
   * `f64.max(..., 1e-30)` guard in {@link Ln.toWat}: that guard exists to
   * keep the *forward* value finite through transient negative states during
   * Newton iterations, not to change what the true derivative is.
   */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Divide([new Num(1), this.child]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Sine. */
export class Sin extends Unary {
  readonly nodeType = "Sin";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.sin(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.sin(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\sin(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><sin/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_sin ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[sin(child)] = cos(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    this.child.pushGradient(mulAdjoint(adjoint, new Cos(this.child)), grads);
  }
}

/** Cosine. */
export class Cos extends Unary {
  readonly nodeType = "Cos";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.cos(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.cos(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\cos(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><cos/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_cos ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[cos(child)] = -sin(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = negAdjoint(new Sin(this.child));
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Tangent. */
export class Tan extends Unary {
  readonly nodeType = "Tan";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.tan(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.tan(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\tan(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><tan/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_tan ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[tan(child)] = sec²(child), built as `sec(child) * sec(child)` rather than `Pow(...,2)` — squaring never needs a power node here. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const sec = new Sec(this.child);
    this.child.pushGradient(mulAdjoint(adjoint, new Mul([sec, sec])), grads);
  }
}

/** Secant, `1 / cos(child)`. */
export class Sec extends Unary {
  readonly nodeType = "Sec";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.cos(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.cos(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\sec(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><sec/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_cos ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[sec(child)] = sec(child)·tan(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Mul([new Sec(this.child), new Tan(this.child)]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Cosecant, `1 / sin(child)`. */
export class Csc extends Unary {
  readonly nodeType = "Csc";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.sin(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.sin(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\csc(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><csc/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_sin ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[csc(child)] = -csc(child)·cot(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = negAdjoint(
      new Mul([new Csc(this.child), new Cot(this.child)]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Cotangent, `1 / tan(child)`. */
export class Cot extends Unary {
  readonly nodeType = "Cot";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.tan(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.tan(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\cot(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><cot/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_tan ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[cot(child)] = -csc²(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const csc = new Csc(this.child);
    const factor = negAdjoint(new Mul([csc, csc]));
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse sine, `arcsin(child)`. */
export class Asin extends Unary {
  readonly nodeType = "Asin";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.asin(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.asin(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\arcsin(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arcsin/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_asin ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[asin(child)] = 1/sqrt(1-child²). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Num(1), new Mul([this.child, this.child])]);
    const factor = new Divide([new Num(1), new Sqrt(radicand, new Num(2))]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse cosine, `arccos(child)`. */
export class Acos extends Unary {
  readonly nodeType = "Acos";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.acos(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.acos(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\arccos(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccos/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_acos ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[acos(child)] = -1/sqrt(1-child²) — negative of {@link Asin.pushGradient}'s factor. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Num(1), new Mul([this.child, this.child])]);
    const factor = negAdjoint(
      new Divide([new Num(1), new Sqrt(radicand, new Num(2))]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse tangent, `arctan(child)`. */
export class Atan extends Unary {
  readonly nodeType = "Atan";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.atan(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.atan(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\arctan(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arctan/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_atan ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[atan(child)] = 1/(1+child²). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Divide([
      new Num(1),
      new Add([new Num(1), new Mul([this.child, this.child])]),
    ]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse cotangent, `arctan(1 / child)`. */
export class Acot extends Unary {
  readonly nodeType = "Acot";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.atan(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.atan(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arccot}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccot/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_atan (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[acot(child)] = -1/(1+child²) — negative of {@link Atan.pushGradient}'s factor. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = negAdjoint(
      new Divide([
        new Num(1),
        new Add([new Num(1), new Mul([this.child, this.child])]),
      ]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse secant, `arccos(1 / child)`. */
export class ArcSec extends Unary {
  readonly nodeType = "ArcSec";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.acos(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.acos(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arcsec}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arcsec/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_acos (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[arcsec(child)] = 1/(|child|·sqrt(child²-1)). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Mul([this.child, this.child]), new Num(1)]);
    const factor = new Divide([
      new Num(1),
      new Mul([new Abs(this.child), new Sqrt(radicand, new Num(2))]),
    ]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse cosecant, `arcsin(1 / child)`. */
export class ArcCsc extends Unary {
  readonly nodeType = "ArcCsc";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.asin(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.asin(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arccsc}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccsc/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_asin (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[arccsc(child)] = -1/(|child|·sqrt(child²-1)) — negative of {@link ArcSec.pushGradient}'s factor. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Mul([this.child, this.child]), new Num(1)]);
    const factor = negAdjoint(
      new Divide([
        new Num(1),
        new Mul([new Abs(this.child), new Sqrt(radicand, new Num(2))]),
      ]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Hyperbolic sine. */
export class Sinh extends Unary {
  readonly nodeType = "Sinh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.sinh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.sinh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\sinh(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><sinh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_sinh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[sinh(child)] = cosh(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    this.child.pushGradient(mulAdjoint(adjoint, new Cosh(this.child)), grads);
  }
}

/** Hyperbolic cosine. */
export class Cosh extends Unary {
  readonly nodeType = "Cosh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.cosh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.cosh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\cosh(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><cosh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_cosh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[cosh(child)] = sinh(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    this.child.pushGradient(mulAdjoint(adjoint, new Sinh(this.child)), grads);
  }
}

/** Hyperbolic tangent. */
export class Tanh extends Unary {
  readonly nodeType = "Tanh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.tanh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.tanh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\tanh(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><tanh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_tanh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[tanh(child)] = sech²(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const sech = new Sech(this.child);
    this.child.pushGradient(mulAdjoint(adjoint, new Mul([sech, sech])), grads);
  }
}

/** Hyperbolic secant, `1 / cosh(child)`. */
export class Sech extends Unary {
  readonly nodeType = "Sech";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.cosh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.cosh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{sech}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><sech/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_cosh ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[sech(child)] = -sech(child)·tanh(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = negAdjoint(
      new Mul([new Sech(this.child), new Tanh(this.child)]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Hyperbolic cosecant, `1 / sinh(child)`. */
export class Csch extends Unary {
  readonly nodeType = "Csch";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.sinh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.sinh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{csch}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><csch/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_sinh ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[csch(child)] = -csch(child)·coth(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = negAdjoint(
      new Mul([new Csch(this.child), new Coth(this.child)]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Hyperbolic cotangent, `1 / tanh(child)`. */
export class Coth extends Unary {
  readonly nodeType = "Coth";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `1 / Math.tanh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `1 / np.tanh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\coth(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><coth/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(f64.div (f64.const 1) (call $math_tanh ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[coth(child)] = -csch²(child). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const csch = new Csch(this.child);
    const factor = negAdjoint(new Mul([csch, csch]));
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic sine, `arcsinh(child)`. */
export class ArcSinh extends Unary {
  readonly nodeType = "ArcSinh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.asinh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.asinh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arcsinh}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arcsinh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_asinh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[asinh(child)] = 1/sqrt(child²+1). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Add([new Mul([this.child, this.child]), new Num(1)]);
    const factor = new Divide([new Num(1), new Sqrt(radicand, new Num(2))]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic cosine, `arccosh(child)`. */
export class ArcCosh extends Unary {
  readonly nodeType = "ArcCosh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.acosh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.acosh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arccosh}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccosh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_acosh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[acosh(child)] = 1/sqrt(child²-1) (domain child>1). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Mul([this.child, this.child]), new Num(1)]);
    const factor = new Divide([new Num(1), new Sqrt(radicand, new Num(2))]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic tangent, `arctanh(child)`. */
export class ArcTanh extends Unary {
  readonly nodeType = "ArcTanh";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.atanh(${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.atanh(${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arctanh}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arctanh/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_atanh ${this.child.toWat(ctx)})`;
  }
  /** d/dchild[atanh(child)] = 1/(1-child²). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Divide([
      new Num(1),
      new Minus([new Num(1), new Mul([this.child, this.child])]),
    ]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic cosecant, `arcsinh(1 / child)`. */
export class ArcCsch extends Unary {
  readonly nodeType = "ArcCsch";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.asinh(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.asinh(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arccsch}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccsch/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_asinh (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[arccsch(child)] = -1/(|child|·sqrt(1+child²)). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Add([new Num(1), new Mul([this.child, this.child])]);
    const factor = negAdjoint(
      new Divide([
        new Num(1),
        new Mul([new Abs(this.child), new Sqrt(radicand, new Num(2))]),
      ]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic secant, `arccosh(1 / child)`. */
export class ArcSech extends Unary {
  readonly nodeType = "ArcSech";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.acosh(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.acosh(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arcsech}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arcsech/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_acosh (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[arcsech(child)] = -1/(child·sqrt(1-child²)) (domain 0&lt;child&lt;1, so no `Abs` needed). */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const radicand = new Minus([new Num(1), new Mul([this.child, this.child])]);
    const factor = negAdjoint(
      new Divide([
        new Num(1),
        new Mul([this.child, new Sqrt(radicand, new Num(2))]),
      ]),
    );
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/** Inverse hyperbolic cotangent, `arctanh(1 / child)`. */
export class ArcCoth extends Unary {
  readonly nodeType = "ArcCoth";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `Math.atanh(1 / ${this.child.toJs()})`;
  }
  toPy(displayNames: Map<string, string>): string {
    return `np.atanh(1 / ${this.child.toPy(displayNames)})`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\text{arccoth}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><arccoth/>${this.child.toSBML()}</apply>`;
  }
  toWat(ctx: WatContext): string {
    return `(call $math_atanh (f64.div (f64.const 1) ${this.child.toWat(ctx)}))`;
  }
  /** d/dchild[arccoth(child)] = 1/(1-child²) — the same closed form as {@link ArcTanh.pushGradient}, valid on the complementary (|child|>1) domain. */
  pushGradient(adjoint: Base, grads: GradMap): void {
    const factor = new Divide([
      new Num(1),
      new Minus([new Num(1), new Mul([this.child, this.child])]),
    ]);
    this.child.pushGradient(mulAdjoint(adjoint, factor), grads);
  }
}

/**
 * The SBML `rateOf` operator, `d(child)/dt`. Only TeX and SBML render it
 * meaningfully; the JS/Python/WAT targets emit `0` (rates are not available in
 * those evaluation contexts).
 */
export class RateOf extends Unary {
  readonly nodeType = "RateOf";
  constructor(public child: Base) {
    super();
  }
  toJs(): string {
    return `0`;
  }
  toPy(_displayNames: Map<string, string>): string {
    return `0`;
  }
  toTex(texNames: Map<string, string>): string {
    return `\\frac{d}{dt}(${this.child.toTex(texNames)})`;
  }
  toSBML(): string {
    return `<apply><csymbol definitionURL="http://www.sbml.org/sbml/symbols/rateOf">rateOf</csymbol>${this.child.toSBML()}</apply>`;
  }
  toWat(_ctx: WatContext): string {
    return `(f64.const 0)`;
  }
  /** Already a literal zero in every numeric backend (see class doc comment); its gradient is trivially zero too, no non-smoothness convention needed. */
  pushGradient(_adjoint: Base, _grads: GradMap): void {}
}
